PUT {{host}}/account/reset-password
Content-Type: application/json

{
  "email": "test@mail.ru",
  "code": "TWH337",
  "password": "11111111"
}

###
POST {{host}}/account/get-code
Content-Type: application/json

{
  "email": "test@mail.ru"
}