POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "andrey@mail.ru",
  "password": "12345678"
}


###
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "QxTXIwrrdNDg_ved9ZrVCd2GSk3HxUIEM94FunX7Gul-2cj_F4UVgC8WIMGo9Nz4-lQwUeT-ro7K2YEZsDOD9zVQGXo0FUmwwmCqfWEPSbdGmsV9a8geWTb553aAp9ZmB7mlOUmVySiq9UOrbxwNT21XaagQrBJ8uHngzynOjGKQVBd50TiUYjSIBk4Wodv0eI0BXF4H"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "vasya@mail.com",
  "password": "12345678"
}
