POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "andrey@mail.ru",
  "password": "12345678"
}

###
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "7fNsBA59wbeoqnZV742CbaiOb77gs40_FJNWe6wwyRGWW8DUgA1t1mREEnhGg30BeIV5pCs6lj6ufNEGDaKJZ0zt7oMAlPZbVBlSvQ_HeTTe0dAKEh8XJmlnqPSJfgoSUqEWpMSC0V5N-3He-500dMo7v7x_gfntU5PGfE3_oYj3RZvOK43CBEY7g7w3JosryTJ1e3bs"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "test@mail.ru",
  "password": "12345678"
}
