DELETE {{host}}/favorites
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1ODE0NzQyLCJleHAiOjE2OTU4MTgzNDIsInVpZCI6Mn0.C9_DKZ42nrUBYkFrdCirD-R_jqgH8OHSQv_LCJrPkSU

{
  "id": 4
}

###
POST {{host}}/favorites
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1ODE0NzQyLCJleHAiOjE2OTU4MTgzNDIsInVpZCI6Mn0.C9_DKZ42nrUBYkFrdCirD-R_jqgH8OHSQv_LCJrPkSU

{
  "cinema_id": 1
}

###
GET {{host}}/favorites
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1ODE0NzQyLCJleHAiOjE2OTU4MTgzNDIsInVpZCI6Mn0.C9_DKZ42nrUBYkFrdCirD-R_jqgH8OHSQv_LCJrPkSU