POST {{host}}/profile/cinema-watched
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1NjU3MTQ3LCJleHAiOjE2OTU2NTc0NDcsInVpZCI6Mn0.BwJpu_edANWSNfesrKDUBMWNaYn8aUN238EumWvYVpY


{
  "cinema_ids": [
    99,
    105
  ]
}