PUT {{host}}/profile/personalization
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1OTk2ODY3LCJleHAiOjE2OTYwMDA0NjcsInVpZCI6Mn0.g6HQtC-KvnTGYvqXMnOmFKna06rpK8bBAewGATeofQc

{
  "sex": "FEMALE",
  "birthday": "21.05.1994",
  "country_id": 2,
  "genre_ids": [
    2,
    3
  ],
  "hobbies_ids": [
    1
  ]
}

###
PUT {{host}}/profile/change-password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1ODI3MTc4LCJleHAiOjE2OTU4MzA3NzgsInVpZCI6Mn0.gasohTy6ka6R80WDbZBFIx2QeE2Im-e3kgiXgHg405U

{
  "currentPassword": "123456789",
  "newPassword": "1111111111"
}

###
PUT {{host}}/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjk1OTk2ODY3LCJleHAiOjE2OTYwMDA0NjcsInVpZCI6Mn0.g6HQtC-KvnTGYvqXMnOmFKna06rpK8bBAewGATeofQc

{
  "surname": "Иванов",
  "name": "Иван",
  "patronymic": "Иванович",
  "vk": "123323",
  "telegram": "user"
}