###
DELETE {{host}}/user/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlVOSVFVRS1KV1QtSURFTlRJRklFUiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmV4YW1wbGUuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2Zyb250ZW5kLmV4YW1wbGUuY29tIiwianRpIjoiVU5JUVVFLUpXVC1JREVOVElGSUVSIiwiaWF0IjoxNjg4MDM0MTM0LCJleHAiOjE2ODgwMzQ0MzQsInVpZCI6OX0.MMA-T26uVO2YvQEtmscbO1ak2lbhol7hcAaCoYM7vEg

{
  "refreshToken": "Too_l_I1yezcp6Wj5t6rnA5CFlKpDVtc7OJ5VIV8n4EpRS7vIZ4EGLW8oNn0if7lyP7LU4fTfBon_pHE19IMWVvclNXn40Fkmpkq_DKHaWz0sXUyoukWkjgKnZiZPes-btDG8FWK6EJJyo5Gzn31ejGZ5c0iLWq0ux9UmpVTmTRa2e7bS-04o7CUAWb-X7l-BbntV8CA"
}